import 'dart:async';
import 'dart:collection';

import 'package:uuid/uuid.dart';

/// Optional category for a Plant.
///
/// Identifiers in English to match DB storage, ARB keys, and enum names —
/// see MISSION.md "Convenzioni di implementazione → Vocabolario".
enum PlantCategory {
  bonsai,
  prebonsai,
  yamadori,
}

/// Type-safe, validated wrapper for a local filesystem path to a plant photo.
///
/// Construction fails fast with [ArgumentError] if [raw] is blank, preventing
/// invalid paths from propagating into the domain or the repository layer.
final class PhotoPath {
  const PhotoPath._(this.value);

  factory PhotoPath(String raw) {
    final trimmed = raw.trim();
    if (trimmed.isEmpty) {
      throw ArgumentError.value(raw, 'raw', 'PhotoPath cannot be empty');
    }
    return PhotoPath._(trimmed);
  }

  /// The underlying path string.
  final String value;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is PhotoPath && other.value == value;

  @override
  int get hashCode => value.hashCode;

  @override
  String toString() => value;
}

class Plant {
  const Plant({
    required this.id,
    required this.species,
    required this.nickname,
    required this.coverPhotoPath,
    required this.createdAt,
    this.category,
    this.position,
    this.substrate,
  });

  final String id;
  final String species;
  final String nickname;

  /// Typed path to the cover photo on the local filesystem.
  /// Resolved from the relative DB path by the repository before returning.
  final PhotoPath coverPhotoPath;

  final DateTime createdAt;
  final PlantCategory? category;
  final String? position;
  final String? substrate;
}

const kSeedSpecies = <String>[
  'Juniperus chinensis',
  'Acer palmatum',
  'Pinus parviflora',
  'Ficus retusa',
  'Ulmus parvifolia',
  'Carpinus turczaninowii',
  'Prunus mume',
  'Zelkova serrata',
  'Cryptomeria japonica',
  'Punica granatum',
];

String defaultNickname(String species, int existingCount, {String? nickname}) {
  if (nickname != null && nickname.trim().isNotEmpty) {
    return nickname;
  }

  final base = species.trim().split(RegExp(r'\s+')).last.toLowerCase();
  final suffix = (existingCount + 1).toString().padLeft(2, '0');
  return '${base}_$suffix';
}

abstract interface class PlantRepository {
  /// Returns all plants ordered by [Plant.createdAt] descending.
  Future<List<Plant>> getAll();

  /// Emits a void event each time the set of plants changes.
  Stream<void> get changes;

  /// Creates and persists a new plant.
  ///
  /// [sourcePhotoPath] is the absolute path of the source photo file
  /// (e.g. a temp file from image_picker). The repository copies it to the
  /// application documents directory and stores the relative path in the DB.
  ///
  /// [nickname] null or blank → auto-generated by [defaultNickname].
  Future<Plant> add({
    required String species,
    String? nickname,
    required String sourcePhotoPath,
  });
}

/// In-memory implementation of [PlantRepository] for development and tests.
///
/// Uses synthetic cover photo paths (`photos/seed_<n>.jpg`) — no real files
/// are created. Safe to use in unit tests and widget tests that do not verify
/// photo rendering.
class InMemoryPlantRepository implements PlantRepository {
  InMemoryPlantRepository({DateTime Function()? now, Uuid? uuid})
    : _now = now ?? DateTime.now,
      _uuid = uuid ?? const Uuid() {
    _seed();
  }

  static const _seedPlants = <(String, String)>[
    ('Juniperus chinensis', 'shohin del terrazzo'),
    ('Acer palmatum', 'acero rosso'),
    ('Pinus parviflora', 'pino delle nevi'),
    ('Ficus retusa', 'ficus veloce'),
    ('Ulmus parvifolia', 'olmo pigro'),
  ];

  final DateTime Function() _now;
  final Uuid _uuid;
  final List<Plant> _plants = <Plant>[];
  final _changesController = StreamController<void>.broadcast();

  @override
  Stream<void> get changes => _changesController.stream;

  @override
  Future<List<Plant>> getAll() async {
    final sorted = List<Plant>.of(_plants)
      ..sort((a, b) => b.createdAt.compareTo(a.createdAt));
    return UnmodifiableListView(sorted);
  }

  @override
  Future<Plant> add({
    required String species,
    String? nickname,
    required String sourcePhotoPath,
  }) async {
    final plant = Plant(
      id: _uuid.v4(),
      species: species,
      nickname: defaultNickname(species, _plants.length, nickname: nickname),
      coverPhotoPath: PhotoPath(sourcePhotoPath),
      createdAt: _now(),
    );

    _plants.add(plant);
    _changesController.add(null);
    return plant;
  }

  void _seed() {
    final anchor = _now();

    for (final (index, seed) in _seedPlants.indexed) {
      _plants.add(
        Plant(
          id: _uuid.v4(),
          species: seed.$1,
          nickname: seed.$2,
          coverPhotoPath: PhotoPath('photos/seed_$index.jpg'),
          createdAt: anchor.subtract(Duration(days: 30 * (index + 1))),
        ),
      );
    }
  }
}
