import 'package:drift/drift.dart';

import 'photos_table.dart';

/// Plants table.
///
/// Schema decided in ticket #34.
/// Indexes: `created_at DESC` (collection grid ordering) and `species`
/// (species-based filtering in the prototype Variant C).
@TableIndex(name: 'plants_created_at_idx', columns: {#createdAt})
@TableIndex(name: 'plants_species_idx', columns: {#species})
class Plants extends Table {
  /// UUID v4 generated client-side.
  TextColumn get id => text()();

  TextColumn get species => text()();

  /// Auto-generated by the repository when blank; invariant: never null or empty.
  TextColumn get nickname =>
      text().customConstraint("NOT NULL CHECK (nickname <> '')")();

  DateTimeColumn get createdAt => dateTime()();

  /// 1:1 FK to Photos — the cover photo for this plant.
  /// UNIQUE enforced at DB level; ON DELETE RESTRICT keeps orphan-prevention
  /// in the repository (must delete photo record last).
  TextColumn get coverPhotoId =>
      text().unique().references(Photos, #id, onDelete: KeyAction.restrict)();

  /// Optional plant category.  CHECK constraint kept at DB level as defence in
  /// depth; the repository also validates before writing.
  TextColumn get category => text().nullable().customConstraint(
    "CHECK (category IN ('bonsai', 'prebonsai', 'yamadori'))",
  )();

  TextColumn get position => text().nullable()();
  TextColumn get substrate => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}
