import 'package:drift/drift.dart';

import '../../../domain/plants.dart';
import 'photos_table.dart';

/// Plants table.
///
/// Schema decided in ticket #34.
/// Indexes: `created_at DESC` (collection grid ordering) and `species`
/// (species-based filtering in the prototype Variant C).
/// Note: plants_created_at_idx is created explicitly in AppDatabase.onCreate
/// with DESC direction — @TableIndex doesn't support column ordering.
@TableIndex(name: 'plants_species_idx', columns: {#species})
class Plants extends Table {
  /// UUID v4 generated client-side.
  TextColumn get id => text()();

  TextColumn get species => text()();

  /// Auto-generated by the repository when blank; invariant: never null or empty.
  TextColumn get nickname =>
      text().customConstraint("NOT NULL CHECK (nickname <> '')")();

  DateTimeColumn get createdAt => dateTime()();

  /// 1:1 FK to Photos — the cover photo for this plant.
  /// UNIQUE enforced at DB level; ON DELETE RESTRICT keeps orphan-prevention
  /// in the repository (must delete photo record last).
  TextColumn get coverPhotoId =>
      text().unique().references(Photos, #id, onDelete: KeyAction.restrict)();

  /// Optional plant category.  [PlantCategory] is the single source of truth —
  /// Drift derives the CHECK constraint and TypeConverter from the enum values.
  TextColumn get category => textEnum<PlantCategory>().nullable()();

  TextColumn get position => text().nullable()();
  TextColumn get substrate => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}
